### ISSUE TITLE
Звуковые символы при шифровании

### ISSUE THREAD

**Issue by kratos23** [EGOVOLdev/Rome-cypher#4]
При вводе шифровании некоторых строк, используются символы, которые при выводе в консоль воспроизводятся как звуки.К примеру последовательность 
![default](https://cloud.githubusercontent.com/assets/12779215/15258625/4c021bb8-1955-11e6-8eaa-fb04dc690655.PNG)
воспроизводит 4-5 звуковых сигналов.

**Comment by EGOVOLdev** [comment]
У меня таких проблем нет, а вот то, что ты запихнул туда ё, это плохо, т.к. с русскими символами что-то не то. Но с фиксом хз -- по твоей философии лучше добавить фичи, а для презентации и так выглядит эффектно...

**Comment by kratos23** [comment]
Я ведь скажу что у тебя с русскими буквами проблема.

**Comment by EGOVOLdev** [comment]
На новом релизе проверь, у меня нет проблем

**Comment by EGOVOLdev** [comment]
Суть в том, что влезают служебные символы до 31ого и оставляют после себя звук, переход на след. строку, пустые места. Ща найду причину

**Comment by EGOVOLdev** [comment]
Причина в том, что пробел и ноль переполняются после того, как становятся 255ым символом и на следующей итерации опять переходят в начало таблицы

**Comment by EGOVOLdev** [comment]
-fixed-

**Comment by kratos23** [comment]
По прежнему звуковые символы при шифровании
